org.eclipse.jdt.core.formatter.tabulation.char=tab
org.eclipse.jdt.core.formatter.tabulation.size=4
org.eclipse.jdt.core.formatter.indentation.size=4
org.eclipse.jdt.core.formatter.continuation_indentation=1
org.eclipse.jdt.core.formatter.continuation_indentation_for_array_initializer=1
org.eclipse.jdt.core.formatter.lineSplit=999
org.eclipse.jdt.core.formatter.join_wrapped_lines=false
org.eclipse.jdt.core.formatter.join_lines_in_comments=false
org.eclipse.jdt.core.formatter.wrap_outer_expressions_when_nested=false
org.eclipse.jdt.core.formatter.text_block_indentation=3
org.eclipse.jdt.core.formatter.parentheses_positions_in_method_invocation=preserve_positions
org.eclipse.jdt.core.formatter.parentheses_positions_in_method_delcaration=preserve_positions
org.eclipse.jdt.core.formatter.parentheses_positions_in_record_declaration=preserve_positions
org.eclipse.jdt.core.formatter.parentheses_positions_in_if_while_statement=preserve_positions
org.eclipse.jdt.core.formatter.parentheses_positions_in_for_statment=preserve_positions
org.eclipse.jdt.core.formatter.parentheses_positions_in_switch_statement=preserve_positions
org.eclipse.jdt.core.formatter.parentheses_positions_in_try_clause=preserve_positions
org.eclipse.jdt.core.formatter.parentheses_positions_in_catch_clause=preserve_positions
org.eclipse.jdt.core.formatter.parentheses_positions_in_annotation=preserve_positions
org.eclipse.jdt.core.formatter.alignment_for_arguments_in_method_invocation=16
org.eclipse.jdt.core.formatter.alignment_for_arguments_in_allocation_expression=16
org.eclipse.jdt.core.formatter.alignment_for_arguments_in_explicit_constructor_call=16
org.eclipse.jdt.core.formatter.alignment_for_arguments_in_qualified_allocation_expression=16
org.eclipse.jdt.core.formatter.alignment_for_parameters_in_method_declaration=16
org.eclipse.jdt.core.formatter.alignment_for_parameters_in_constructor_declaration=16
org.eclipse.jdt.core.formatter.alignment_for_record_components=16
org.eclipse.jdt.core.formatter.alignment_for_selector_in_method_invocation=16
org.eclipse.jdt.core.formatter.alignment_for_conditional_expression=16
org.eclipse.jdt.core.formatter.alignment_for_conditional_expression_chain=16
org.eclipse.jdt.core.formatter.alignment_for_annotations_on_local_variable=0
org.eclipse.jdt.core.formatter.alignment_for_type_annotations=0
org.eclipse.jdt.core.formatter.alignment_for_enum_constants=16
org.eclipse.jdt.core.formatter.insert_new_line_after_annotation_on_type=insert
org.eclipse.jdt.core.formatter.insert_new_line_after_annotation_on_field=insert
org.eclipse.jdt.core.formatter.insert_new_line_after_annotation_on_method=insert
org.eclipse.jdt.core.formatter.insert_new_line_after_annotation_on_package=insert
org.eclipse.jdt.core.formatter.insert_new_line_after_annotation_on_enum_constant=insert
org.eclipse.jdt.core.formatter.insert_new_line_after_annotation_on_local_variable=insert
org.eclipse.jdt.core.formatter.insert_new_line_after_type_annotation=do not insert
org.eclipse.jdt.core.formatter.keep_if_then_body_block_on_one_line=one_line_if_empty
org.eclipse.jdt.core.formatter.keep_loop_body_block_on_one_line=one_line_if_empty
org.eclipse.jdt.core.formatter.keep_code_block_on_one_line=one_line_if_empty
org.eclipse.jdt.core.formatter.keep_switch_body_block_on_one_line=one_line_if_empty
org.eclipse.jdt.core.formatter.keep_switch_case_with_arrow_on_one_line=one_line_if_empty
org.eclipse.jdt.core.formatter.keep_method_body_on_one_line=one_line_preserve
org.eclipse.jdt.core.formatter.keep_lambda_body_block_on_one_line=one_line_preserve
org.eclipse.jdt.core.formatter.keep_type_declaration_on_one_line=one_line_preserve
org.eclipse.jdt.core.formatter.keep_anonymous_type_declaration_on_one_line=one_line_preserve
org.eclipse.jdt.core.formatter.keep_enum_constant_declaration_on_one_line=one_line_preserve
org.eclipse.jdt.core.formatter.keep_enum_declaration_on_one_line=one_line_preserve
org.eclipse.jdt.core.formatter.keep_record_constructor_on_one_line=one_line_preserve
org.eclipse.jdt.core.formatter.keep_record_declaration_on_one_line=one_line_preserve
org.eclipse.jdt.core.formatter.comment.format_javadoc_comments=false
org.eclipse.jdt.core.formatter.comment.format_block_comments=false
org.eclipse.jdt.core.formatter.comment.format_line_comments=false
